export const HAMBURGER_BUTTON_ID = 'HAMBURGER_BUTTON_ID';
export const TOP_RIGHT_BUTTON_ID = 'TOP_RIGHT_BUTTON_ID';
export const SIDE_MENU_ID = 'SIDE_MENU_ID';
export const BOTTOM_TAB_ID = 'BOTTOM_TAB_ID';
export const BOTTOM_TAB_STACK_ID = 'BOTTOM_TAB_STACK_ID';
export const MODAL_DISMISS_BUTTON_ID = 'MODAL_DISMISS_BUTTON_ID';
export const PRODUCT_CARD_TYPES = {
	HORIZONTAL:'HORIZONTAL',
	VERTICAL: 'VERTICAL'
}